'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace WSPORTALMVP
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="STRAUTUSER", [Namespace]:="http://localhost:69/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class STRAUTUSER
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private REGEMAILField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private REGNOMEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private REGPERFILField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private REGSENHAField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private USERLOGINField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private USERSENHAField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private USERTIPOField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property REGEMAIL() As String
            Get
                Return Me.REGEMAILField
            End Get
            Set
                If (Object.ReferenceEquals(Me.REGEMAILField, value) <> true) Then
                    Me.REGEMAILField = value
                    Me.RaisePropertyChanged("REGEMAIL")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property REGNOME() As String
            Get
                Return Me.REGNOMEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.REGNOMEField, value) <> true) Then
                    Me.REGNOMEField = value
                    Me.RaisePropertyChanged("REGNOME")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property REGPERFIL() As String
            Get
                Return Me.REGPERFILField
            End Get
            Set
                If (Object.ReferenceEquals(Me.REGPERFILField, value) <> true) Then
                    Me.REGPERFILField = value
                    Me.RaisePropertyChanged("REGPERFIL")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property REGSENHA() As String
            Get
                Return Me.REGSENHAField
            End Get
            Set
                If (Object.ReferenceEquals(Me.REGSENHAField, value) <> true) Then
                    Me.REGSENHAField = value
                    Me.RaisePropertyChanged("REGSENHA")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property USERLOGIN() As String
            Get
                Return Me.USERLOGINField
            End Get
            Set
                If (Object.ReferenceEquals(Me.USERLOGINField, value) <> true) Then
                    Me.USERLOGINField = value
                    Me.RaisePropertyChanged("USERLOGIN")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property USERSENHA() As String
            Get
                Return Me.USERSENHAField
            End Get
            Set
                If (Object.ReferenceEquals(Me.USERSENHAField, value) <> true) Then
                    Me.USERSENHAField = value
                    Me.RaisePropertyChanged("USERSENHA")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property USERTIPO() As String
            Get
                Return Me.USERTIPOField
            End Get
            Set
                If (Object.ReferenceEquals(Me.USERTIPOField, value) <> true) Then
                    Me.USERTIPOField = value
                    Me.RaisePropertyChanged("USERTIPO")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DADOSUSUARIO", [Namespace]:="http://localhost:69/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DADOSUSUARIO
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CODIGOField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CPFField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ERROField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private LOJAField As String
        
        Private LRETField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NOMEField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NOMECOMPLETOField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TIPOUSERField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property CODIGO() As String
            Get
                Return Me.CODIGOField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CODIGOField, value) <> true) Then
                    Me.CODIGOField = value
                    Me.RaisePropertyChanged("CODIGO")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property CPF() As String
            Get
                Return Me.CPFField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CPFField, value) <> true) Then
                    Me.CPFField = value
                    Me.RaisePropertyChanged("CPF")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property ERRO() As String
            Get
                Return Me.ERROField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ERROField, value) <> true) Then
                    Me.ERROField = value
                    Me.RaisePropertyChanged("ERRO")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property LOJA() As String
            Get
                Return Me.LOJAField
            End Get
            Set
                If (Object.ReferenceEquals(Me.LOJAField, value) <> true) Then
                    Me.LOJAField = value
                    Me.RaisePropertyChanged("LOJA")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property LRET() As Boolean
            Get
                Return Me.LRETField
            End Get
            Set
                If (Me.LRETField.Equals(value) <> true) Then
                    Me.LRETField = value
                    Me.RaisePropertyChanged("LRET")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property NOME() As String
            Get
                Return Me.NOMEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NOMEField, value) <> true) Then
                    Me.NOMEField = value
                    Me.RaisePropertyChanged("NOME")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property NOMECOMPLETO() As String
            Get
                Return Me.NOMECOMPLETOField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NOMECOMPLETOField, value) <> true) Then
                    Me.NOMECOMPLETOField = value
                    Me.RaisePropertyChanged("NOMECOMPLETO")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property TIPOUSER() As String
            Get
                Return Me.TIPOUSERField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TIPOUSERField, value) <> true) Then
                    Me.TIPOUSERField = value
                    Me.RaisePropertyChanged("TIPOUSER")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="STRGETDBCC", [Namespace]:="http://localhost:69/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class STRGETDBCC
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BUSCAField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FILIALField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private INDICEField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property BUSCA() As String
            Get
                Return Me.BUSCAField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BUSCAField, value) <> true) Then
                    Me.BUSCAField = value
                    Me.RaisePropertyChanged("BUSCA")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property FILIAL() As String
            Get
                Return Me.FILIALField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FILIALField, value) <> true) Then
                    Me.FILIALField = value
                    Me.RaisePropertyChanged("FILIAL")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property INDICE() As String
            Get
                Return Me.INDICEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.INDICEField, value) <> true) Then
                    Me.INDICEField = value
                    Me.RaisePropertyChanged("INDICE")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="STRRETXML", [Namespace]:="http://localhost:69/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class STRRETXML
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private XMLField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, EmitDefaultValue:=false)>  _
        Public Property XML() As String
            Get
                Return Me.XMLField
            End Get
            Set
                If (Object.ReferenceEquals(Me.XMLField, value) <> true) Then
                    Me.XMLField = value
                    Me.RaisePropertyChanged("XML")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="STRGETDBSRA", [Namespace]:="http://localhost:69/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class STRGETDBSRA
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BUSCAField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FILIALField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private INDICEField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property BUSCA() As String
            Get
                Return Me.BUSCAField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BUSCAField, value) <> true) Then
                    Me.BUSCAField = value
                    Me.RaisePropertyChanged("BUSCA")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property FILIAL() As String
            Get
                Return Me.FILIALField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FILIALField, value) <> true) Then
                    Me.FILIALField = value
                    Me.RaisePropertyChanged("FILIAL")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property INDICE() As String
            Get
                Return Me.INDICEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.INDICEField, value) <> true) Then
                    Me.INDICEField = value
                    Me.RaisePropertyChanged("INDICE")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="STRGETSRA", [Namespace]:="http://localhost:69/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class STRGETSRA
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private BUSCAField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FILIALField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private INDICEField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property BUSCA() As String
            Get
                Return Me.BUSCAField
            End Get
            Set
                If (Object.ReferenceEquals(Me.BUSCAField, value) <> true) Then
                    Me.BUSCAField = value
                    Me.RaisePropertyChanged("BUSCA")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property FILIAL() As String
            Get
                Return Me.FILIALField
            End Get
            Set
                If (Object.ReferenceEquals(Me.FILIALField, value) <> true) Then
                    Me.FILIALField = value
                    Me.RaisePropertyChanged("FILIAL")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property INDICE() As String
            Get
                Return Me.INDICEField
            End Get
            Set
                If (Object.ReferenceEquals(Me.INDICEField, value) <> true) Then
                    Me.INDICEField = value
                    Me.RaisePropertyChanged("INDICE")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://localhost:69/", ConfigurationName:="WSPORTALMVP.PORTALMVPSOAP")>  _
    Public Interface PORTALMVPSOAP
        
        'CODEGEN: Generating message contract since the wrapper name (AUTHUSERSIGARESPONSE) of message AUTHUSERSIGAResponse does not match the default value (AUTHUSERSIGA)
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost:69/AUTHUSERSIGA", ReplyAction:="*")>  _
        Function AUTHUSERSIGA(ByVal request As WSPORTALMVP.AUTHUSERSIGARequest) As WSPORTALMVP.AUTHUSERSIGAResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost:69/AUTHUSERSIGA", ReplyAction:="*")>  _
        Function AUTHUSERSIGAAsync(ByVal request As WSPORTALMVP.AUTHUSERSIGARequest) As System.Threading.Tasks.Task(Of WSPORTALMVP.AUTHUSERSIGAResponse)
        
        'CODEGEN: Generating message contract since the wrapper name (GETDBCCRESPONSE) of message GETDBCCResponse does not match the default value (GETDBCC)
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost:69/GETDBCC", ReplyAction:="*")>  _
        Function GETDBCC(ByVal request As WSPORTALMVP.GETDBCCRequest) As WSPORTALMVP.GETDBCCResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost:69/GETDBCC", ReplyAction:="*")>  _
        Function GETDBCCAsync(ByVal request As WSPORTALMVP.GETDBCCRequest) As System.Threading.Tasks.Task(Of WSPORTALMVP.GETDBCCResponse)
        
        'CODEGEN: Generating message contract since the wrapper name (GETDBSRARESPONSE) of message GETDBSRAResponse does not match the default value (GETDBSRA)
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost:69/GETDBSRA", ReplyAction:="*")>  _
        Function GETDBSRA(ByVal request As WSPORTALMVP.GETDBSRARequest) As WSPORTALMVP.GETDBSRAResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost:69/GETDBSRA", ReplyAction:="*")>  _
        Function GETDBSRAAsync(ByVal request As WSPORTALMVP.GETDBSRARequest) As System.Threading.Tasks.Task(Of WSPORTALMVP.GETDBSRAResponse)
        
        'CODEGEN: Generating message contract since the wrapper name (GETSRARESPONSE) of message GETSRAResponse does not match the default value (GETSRA)
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost:69/GETSRA", ReplyAction:="*")>  _
        Function GETSRA(ByVal request As WSPORTALMVP.GETSRARequest) As WSPORTALMVP.GETSRAResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost:69/GETSRA", ReplyAction:="*")>  _
        Function GETSRAAsync(ByVal request As WSPORTALMVP.GETSRARequest) As System.Threading.Tasks.Task(Of WSPORTALMVP.GETSRAResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="AUTHUSERSIGA", WrapperNamespace:="http://localhost:69/", IsWrapped:=true)>  _
    Partial Public Class AUTHUSERSIGARequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://localhost:69/", Order:=0)>  _
        Public AUTUSER As WSPORTALMVP.STRAUTUSER
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AUTUSER As WSPORTALMVP.STRAUTUSER)
            MyBase.New
            Me.AUTUSER = AUTUSER
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="AUTHUSERSIGARESPONSE", WrapperNamespace:="http://localhost:69/", IsWrapped:=true)>  _
    Partial Public Class AUTHUSERSIGAResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://localhost:69/", Order:=0)>  _
        Public AUTHUSERSIGARESULT As WSPORTALMVP.DADOSUSUARIO
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AUTHUSERSIGARESULT As WSPORTALMVP.DADOSUSUARIO)
            MyBase.New
            Me.AUTHUSERSIGARESULT = AUTHUSERSIGARESULT
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GETDBCC", WrapperNamespace:="http://localhost:69/", IsWrapped:=true)>  _
    Partial Public Class GETDBCCRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://localhost:69/", Order:=0)>  _
        Public PRMGETDBCC As WSPORTALMVP.STRGETDBCC
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal PRMGETDBCC As WSPORTALMVP.STRGETDBCC)
            MyBase.New
            Me.PRMGETDBCC = PRMGETDBCC
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GETDBCCRESPONSE", WrapperNamespace:="http://localhost:69/", IsWrapped:=true)>  _
    Partial Public Class GETDBCCResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://localhost:69/", Order:=0)>  _
        Public GETDBCCRESULT As WSPORTALMVP.STRRETXML
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GETDBCCRESULT As WSPORTALMVP.STRRETXML)
            MyBase.New
            Me.GETDBCCRESULT = GETDBCCRESULT
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GETDBSRA", WrapperNamespace:="http://localhost:69/", IsWrapped:=true)>  _
    Partial Public Class GETDBSRARequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://localhost:69/", Order:=0)>  _
        Public PRMGETDBSRA As WSPORTALMVP.STRGETDBSRA
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal PRMGETDBSRA As WSPORTALMVP.STRGETDBSRA)
            MyBase.New
            Me.PRMGETDBSRA = PRMGETDBSRA
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GETDBSRARESPONSE", WrapperNamespace:="http://localhost:69/", IsWrapped:=true)>  _
    Partial Public Class GETDBSRAResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://localhost:69/", Order:=0)>  _
        Public GETDBSRARESULT As WSPORTALMVP.STRRETXML
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GETDBSRARESULT As WSPORTALMVP.STRRETXML)
            MyBase.New
            Me.GETDBSRARESULT = GETDBSRARESULT
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GETSRA", WrapperNamespace:="http://localhost:69/", IsWrapped:=true)>  _
    Partial Public Class GETSRARequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://localhost:69/", Order:=0)>  _
        Public PRMGETSRA As WSPORTALMVP.STRGETSRA
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal PRMGETSRA As WSPORTALMVP.STRGETSRA)
            MyBase.New
            Me.PRMGETSRA = PRMGETSRA
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="GETSRARESPONSE", WrapperNamespace:="http://localhost:69/", IsWrapped:=true)>  _
    Partial Public Class GETSRAResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://localhost:69/", Order:=0)>  _
        Public GETSRARESULT As WSPORTALMVP.STRRETXML
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GETSRARESULT As WSPORTALMVP.STRRETXML)
            MyBase.New
            Me.GETSRARESULT = GETSRARESULT
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface PORTALMVPSOAPChannel
        Inherits WSPORTALMVP.PORTALMVPSOAP, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class PORTALMVPSOAPClient
        Inherits System.ServiceModel.ClientBase(Of WSPORTALMVP.PORTALMVPSOAP)
        Implements WSPORTALMVP.PORTALMVPSOAP
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSPORTALMVP_PORTALMVPSOAP_AUTHUSERSIGA(ByVal request As WSPORTALMVP.AUTHUSERSIGARequest) As WSPORTALMVP.AUTHUSERSIGAResponse Implements WSPORTALMVP.PORTALMVPSOAP.AUTHUSERSIGA
            Return MyBase.Channel.AUTHUSERSIGA(request)
        End Function
        
        Public Function AUTHUSERSIGA(ByVal AUTUSER As WSPORTALMVP.STRAUTUSER) As WSPORTALMVP.DADOSUSUARIO
            Dim inValue As WSPORTALMVP.AUTHUSERSIGARequest = New WSPORTALMVP.AUTHUSERSIGARequest()
            inValue.AUTUSER = AUTUSER
            Dim retVal As WSPORTALMVP.AUTHUSERSIGAResponse = CType(Me,WSPORTALMVP.PORTALMVPSOAP).AUTHUSERSIGA(inValue)
            Return retVal.AUTHUSERSIGARESULT
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSPORTALMVP_PORTALMVPSOAP_AUTHUSERSIGAAsync(ByVal request As WSPORTALMVP.AUTHUSERSIGARequest) As System.Threading.Tasks.Task(Of WSPORTALMVP.AUTHUSERSIGAResponse) Implements WSPORTALMVP.PORTALMVPSOAP.AUTHUSERSIGAAsync
            Return MyBase.Channel.AUTHUSERSIGAAsync(request)
        End Function
        
        Public Function AUTHUSERSIGAAsync(ByVal AUTUSER As WSPORTALMVP.STRAUTUSER) As System.Threading.Tasks.Task(Of WSPORTALMVP.AUTHUSERSIGAResponse)
            Dim inValue As WSPORTALMVP.AUTHUSERSIGARequest = New WSPORTALMVP.AUTHUSERSIGARequest()
            inValue.AUTUSER = AUTUSER
            Return CType(Me,WSPORTALMVP.PORTALMVPSOAP).AUTHUSERSIGAAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSPORTALMVP_PORTALMVPSOAP_GETDBCC(ByVal request As WSPORTALMVP.GETDBCCRequest) As WSPORTALMVP.GETDBCCResponse Implements WSPORTALMVP.PORTALMVPSOAP.GETDBCC
            Return MyBase.Channel.GETDBCC(request)
        End Function
        
        Public Function GETDBCC(ByVal PRMGETDBCC As WSPORTALMVP.STRGETDBCC) As WSPORTALMVP.STRRETXML
            Dim inValue As WSPORTALMVP.GETDBCCRequest = New WSPORTALMVP.GETDBCCRequest()
            inValue.PRMGETDBCC = PRMGETDBCC
            Dim retVal As WSPORTALMVP.GETDBCCResponse = CType(Me,WSPORTALMVP.PORTALMVPSOAP).GETDBCC(inValue)
            Return retVal.GETDBCCRESULT
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSPORTALMVP_PORTALMVPSOAP_GETDBCCAsync(ByVal request As WSPORTALMVP.GETDBCCRequest) As System.Threading.Tasks.Task(Of WSPORTALMVP.GETDBCCResponse) Implements WSPORTALMVP.PORTALMVPSOAP.GETDBCCAsync
            Return MyBase.Channel.GETDBCCAsync(request)
        End Function
        
        Public Function GETDBCCAsync(ByVal PRMGETDBCC As WSPORTALMVP.STRGETDBCC) As System.Threading.Tasks.Task(Of WSPORTALMVP.GETDBCCResponse)
            Dim inValue As WSPORTALMVP.GETDBCCRequest = New WSPORTALMVP.GETDBCCRequest()
            inValue.PRMGETDBCC = PRMGETDBCC
            Return CType(Me,WSPORTALMVP.PORTALMVPSOAP).GETDBCCAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSPORTALMVP_PORTALMVPSOAP_GETDBSRA(ByVal request As WSPORTALMVP.GETDBSRARequest) As WSPORTALMVP.GETDBSRAResponse Implements WSPORTALMVP.PORTALMVPSOAP.GETDBSRA
            Return MyBase.Channel.GETDBSRA(request)
        End Function
        
        Public Function GETDBSRA(ByVal PRMGETDBSRA As WSPORTALMVP.STRGETDBSRA) As WSPORTALMVP.STRRETXML
            Dim inValue As WSPORTALMVP.GETDBSRARequest = New WSPORTALMVP.GETDBSRARequest()
            inValue.PRMGETDBSRA = PRMGETDBSRA
            Dim retVal As WSPORTALMVP.GETDBSRAResponse = CType(Me,WSPORTALMVP.PORTALMVPSOAP).GETDBSRA(inValue)
            Return retVal.GETDBSRARESULT
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSPORTALMVP_PORTALMVPSOAP_GETDBSRAAsync(ByVal request As WSPORTALMVP.GETDBSRARequest) As System.Threading.Tasks.Task(Of WSPORTALMVP.GETDBSRAResponse) Implements WSPORTALMVP.PORTALMVPSOAP.GETDBSRAAsync
            Return MyBase.Channel.GETDBSRAAsync(request)
        End Function
        
        Public Function GETDBSRAAsync(ByVal PRMGETDBSRA As WSPORTALMVP.STRGETDBSRA) As System.Threading.Tasks.Task(Of WSPORTALMVP.GETDBSRAResponse)
            Dim inValue As WSPORTALMVP.GETDBSRARequest = New WSPORTALMVP.GETDBSRARequest()
            inValue.PRMGETDBSRA = PRMGETDBSRA
            Return CType(Me,WSPORTALMVP.PORTALMVPSOAP).GETDBSRAAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSPORTALMVP_PORTALMVPSOAP_GETSRA(ByVal request As WSPORTALMVP.GETSRARequest) As WSPORTALMVP.GETSRAResponse Implements WSPORTALMVP.PORTALMVPSOAP.GETSRA
            Return MyBase.Channel.GETSRA(request)
        End Function
        
        Public Function GETSRA(ByVal PRMGETSRA As WSPORTALMVP.STRGETSRA) As WSPORTALMVP.STRRETXML
            Dim inValue As WSPORTALMVP.GETSRARequest = New WSPORTALMVP.GETSRARequest()
            inValue.PRMGETSRA = PRMGETSRA
            Dim retVal As WSPORTALMVP.GETSRAResponse = CType(Me,WSPORTALMVP.PORTALMVPSOAP).GETSRA(inValue)
            Return retVal.GETSRARESULT
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSPORTALMVP_PORTALMVPSOAP_GETSRAAsync(ByVal request As WSPORTALMVP.GETSRARequest) As System.Threading.Tasks.Task(Of WSPORTALMVP.GETSRAResponse) Implements WSPORTALMVP.PORTALMVPSOAP.GETSRAAsync
            Return MyBase.Channel.GETSRAAsync(request)
        End Function
        
        Public Function GETSRAAsync(ByVal PRMGETSRA As WSPORTALMVP.STRGETSRA) As System.Threading.Tasks.Task(Of WSPORTALMVP.GETSRAResponse)
            Dim inValue As WSPORTALMVP.GETSRARequest = New WSPORTALMVP.GETSRARequest()
            inValue.PRMGETSRA = PRMGETSRA
            Return CType(Me,WSPORTALMVP.PORTALMVPSOAP).GETSRAAsync(inValue)
        End Function
    End Class
End Namespace
