'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class registration

    '''<summary>
    '''inptNome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inptNome As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''inptEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inptEmail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''drpListTpAcesso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpListTpAcesso As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''inptSenha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inptSenha As Global.System.Web.UI.HtmlControls.HtmlInputPassword

    '''<summary>
    '''inptSenhaVl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents inptSenhaVl As Global.System.Web.UI.HtmlControls.HtmlInputPassword

    '''<summary>
    '''BtnRegistrar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnRegistrar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lblUserError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUserError As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblRet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRet As Global.System.Web.UI.WebControls.Label
End Class
