'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class sra_Gestao

    '''<summary>
    '''dlistIndice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlistIndice As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtBusca control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBusca As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSeek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSeek As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''dlistPageSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlistPageSize As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnNovoFunc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNovoFunc As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''divGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divGridView As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''GVItens control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GVItens As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''divX9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divX9 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''DetalhesField control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DetalhesField As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RA_FILIAL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RA_FILIAL As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''RA_MAT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RA_MAT As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''RA_NOME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RA_NOME As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''RA_NASC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RA_NASC As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''RA_CC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RA_CC As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''RA_ADMISSA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RA_ADMISSA As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''RA_CIC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RA_CIC As Global.System.Web.UI.HtmlControls.HtmlInputText
End Class
